### ISSUE TITLE
Can't install with ansible-galaxy collection

### ISSUE THREAD

**Issue by repomaa** [inwx/ansible-collection#1]
I tried several things:

- `ansible-galaxy collection instal inwx.collection`
- `ansible-galazy collection install https://github.com/inwx/ansible-collection`
- `ansible-galaxy collection install https://github.com/inwx/ansible-collection/archive/master.tar.gz`

The last one I think were closest to success but fails with `"does not contain the required file MANIFEST.json"`

**Comment by NickUfer** [comment]
Hey, we are still in the process of uploading this collection to ansible galaxy. Currently we are waiting for ansible-galaxy to assign to us the `inwx` namespace. Without this namespace we cannot upload the collection. The ticket for the namespace assignment: https://github.com/ansible/galaxy/issues/2251

Anyway, your commands suggest that you can install a collection via an url...I didn't know that was possible. I will try to create a release with a correctly packaged collection so that you may install the collection this way.

**Comment by NickUfer** [comment]
Okay, you should now be able to install the collection:
```
ansible-galaxy collection install https://github.com/inwx/ansible-collection/releases/download/1.0.0/inwx-collection-1.0.0.tar.gz
```

**Comment by repomaa** [comment]
Thanks!
